import './globals.css'
import { Inter,Poppins } from 'next/font/google'

const inter = Poppins({ subsets: ['latin'],weight:"700"})

export const metadata = {
  title: 'Tenzin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
